config/routes.rb
Rails.application.routes.draw do
  
  get 'cities/new'

  root  'static_pages#home'
  
  get   'home'  => 'static_pages#home'
  get   'about' => 'static_pages#about'
  get   'contact' => 'static_pages#contact'
  get   'data' => 'cities#graph' #, :defaults => { :format => 'json' }
  
  resources :cities
  resources :city_names
  resources :industries
  

end

app/models/city.rb
class City < ActiveRecord::Base
  
  belongs_to :city_name
  
end

app/models/city_name.rb
class CityName < ActiveRecord::Base
  has_many :cities
  def display_name
    "#{name}"
  end
end

app/models/industry.rb
class Industry < ActiveRecord::Base
  has_many :cities
  def display_name
    "#{name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def new
  end
  
  
  def graph
    @city =  City.where(name: "LA").select(:midsalary).as_json
    # to do: send @ city to the d3 ajax function 
    respond_to do |format|
      format.json {
        render :json => [1,2,3,4,5]
      }
    end
  end
  
end

app/controllers/city_names_controller.rb
class CityNamesController < ApplicationController
  def new
  end
end

app/controllers/industries_controller.rb
class IndustriesController < ApplicationController
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @city = City.new
  end

  def about
  end
  
  def contact
  end
  
  def data
    @city = City.new(params[:city])
    respond_to do |format|
      format.json {
        render :json => [1,2,3,4,5]
      }
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/city_names_helper.rb
module CityNamesHelper
end

app/helpers/industries_helper.rb
module IndustriesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/cities/new.html.erb
<h1>Cities#new</h1>
<p>Find me in app/views/cities/new.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a <%= link_to "Xi Project",   about_path %> </a> 
    is brought to you by Michael Busch and Michael Nip.
    Check us out on <a href="https://github.com/xi-project-team">github</a>.
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_graph.html.erb
<script>
	draw(@array)
</script>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Xi Project", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "About",   about_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>XiProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim'%>
  <script type="text/javascript" src="http://d3js.org/d3.v3.min.js"></script>
  <script type="text/javascript" src="http://d3js.org/topojson.v0.min.js"></script>
</head>
<body>
<%= render 'layouts/header'%>
<div class="container">
	<%= yield %>
	<%= render 'layouts/footer'%>
</div>
</body>
</html>

app/views/static_pages/about.html.erb
<h1>About the Xi Project</h1>
<p>We wanted a way to play around with data technologies, and created this website as a platform to do that.</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<p>Play around with our data visualization app.</p>
<div class="container">
	<%= form_for @city , url: data_path, :remote => true, method: :get do |f| %>
	<div class"control-group">
		<%= f.label :city, class: 'control-label'%>
		<div class='controls'>
			<%= collection_select( :city, :name, CityName.all, :name, :display_name, {}, {:multiple => false} )%>
		</div>
	</div>
	<div class"control-group">
		<%= f.label :industry, class: 'control-label'%>
		<div class='controls'>
			<%= collection_select( :city, :industry, Industry.all, :name, :display_name, {}, {:multiple => false} )%>
		</div>
	</div>
	<div class"control-group">
		<%= f.label "Display Data", class: 'control-label'%>
		<div class='controls'>
			<%= f.radio_button :midsalary, 'midsalary', :checked => true %>
			<%= f.label :midsalary, 'Median Salary', :value => 'midsalary'%>
			<%= f.radio_button :midsalary, 'midsalary' %>
			<%= f.label :midsalary, 'Not Median Salary', :value => 'midsalary'%>
		</div>
	</div>
	<%= f.submit "Plot" %>
	<% end %>
</div>
<svg id="graph">
</svg> 